"""blogpost model modified again

Revision ID: 3a6c1d437b02
Revises: 414cdce49728
Create Date: 2024-01-03 15:25:04.937244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a6c1d437b02'
down_revision = '414cdce49728'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.drop_column('middle_link')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('middle_link', sa.TEXT(), nullable=False))

    # ### end Alembic commands ###
