"""slug modification in BlogPost model

Revision ID: 7acb700f87cd
Revises: f339b20d6185
Create Date: 2024-01-02 10:49:08.798893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7acb700f87cd'
down_revision = 'f339b20d6185'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_img')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_img', sa.VARCHAR(length=150), nullable=True))

    # ### end Alembic commands ###
